Support for OnlyNotifyWithAttributes
StrangeLoopGames/PropertyChanged pull request #1
Opened 2022-01-20 12:54 UTC by mirasrael

Added support for explicit specifying properties which should emit PropertyChanged event with custom attributes.
If config has OnlyNotifyWithAttributes with comma separate list of full attribute names like:
```xml
<PropertyChanged OnlyNotifyWithAttributes="System.ComponentModel.DisplayNameAttribute,System.ComponentModel.DescriptionAttribute"/>
```
then only these properties will be weaved for OnPropertyChanged invocation. 
Unlike [DoNotNotify] properties without attribute will still behave same for all other aspects: triggering dependent properties and calling `On_PropertyName_Changed` methods.

Related issue: https://app.clickup.com/t/10591183/ECO-17508

2022-01-20 19:38 UTC, johnkslg requested changes

2022-01-20 19:38 UTC, johnkslg commented on PropertyChanged.Fody/NoOwnNotifyProcessing.cs
> +public partial class ModuleWeaver
comments

2022-01-20 19:38 UTC, johnkslg commented on TestAssemblies/AssemblyWithPropertyAttributes/ClassWithAttributedProperties.cs
> +public class ClassWithAttributedProperties : INotifyPropertyChanged
comments here and all classes
we'll need to support this code forever so good to have it fully commented up and keep wiki updated

2022-01-21 07:13 UTC, johnkslg approved these changes

2022-01-21 07:34 UTC, mirasrael commented
Added comments for own modifications.

2022-01-21 07:47 UTC, merged